name: clang-tidy-review

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: ZedThree/clang-tidy-review@v0.13.0
      id: review

    # Uploads an artifact containing clang_fixes.json
    - uses: ZedThree/clang-tidy-review/upload@v0.13.0
      id: upload-review

    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
